import { ArrowLeft, ArrowLeftRight, Pencil } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getTransactionDetail } from "@/db/business-queries";
import { formatDate, formatPKR } from "@/lib/utils";
import { deleteTransactionAction } from "@/app/actions/business";
import { DeleteButton } from "@/components/delete-button";
import { WhatsAppLedgerButton } from "@/components/whatsapp-ledger-button";

export const metadata: Metadata = { title: "Transaction Details" };

export default async function TransactionDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const item = await getTransactionDetail(id);
  if (!item) notFound();

  const whatsappMessage = [
    "Crown Accumulator - Transaction Receipt",
    `Transaction: ${item.number}`,
    `Type: ${item.type.replaceAll("_", " ")}`,
    `Amount: ${formatPKR(item.amount)}`,
    `Date: ${formatDate(item.date)}`,
    item.productName ? `Product: ${item.productName}` : null,
    item.quantity ? `Quantity: ${Number(item.quantity).toLocaleString()} @ ${formatPKR(item.unitPrice)}` : null,
    `Payment: ${item.paymentMethod}`,
    `Description: ${item.description}`,
    "Thank you. This receipt was generated by Crown Accumulator Management System.",
  ].filter(Boolean).join("\n");

  return (
    <main className="page form-page">
      <div className="back-title">
        <Link
          className="icon-button"
          href="/transactions"
          aria-label="Back to transactions"
        >
          <ArrowLeft size={22} />
        </Link>
        <div>
          <div className="eyebrow">Posted transaction</div>
          <h1 className="page-title">{item.number}</h1>
          <p className="page-description">{item.description}</p>
        </div>
        <div className="card-actions detail-actions">
          <WhatsAppLedgerButton phone={item.partyPhone} message={whatsappMessage} />
          <Link className="button button-secondary" href={`/transactions/${id}/edit`}><Pencil size={16} /> Edit</Link>
          <DeleteButton action={deleteTransactionAction.bind(null, id)} confirmMessage={`Delete ${item.number} and reverse its stock and accounting effects?`} label={`Delete ${item.number}`} />
        </div>
      </div>
      <section className="card panel transaction-detail">
        <span className="table-icon green">
          <ArrowLeftRight size={20} />
        </span>
        <dl className="transaction-detail-grid">
          <div>
            <dt>Type</dt>
            <dd>{item.type.replaceAll("_", " ")}</dd>
          </div>
          <div>
            <dt>Status</dt>
            <dd>{item.status}</dd>
          </div>
          <div>
            <dt>Date</dt>
            <dd>{formatDate(item.date)}</dd>
          </div>
          <div>
            <dt>Party / Account</dt>
            <dd>{item.partyName || item.bankName || "—"}</dd>
          </div>
          <div>
            <dt>Product</dt>
            <dd>{item.productName || "Custom transaction"}</dd>
          </div>
          <div>
            <dt>Quantity</dt>
            <dd>{item.quantity ? Number(item.quantity).toLocaleString() : "—"}</dd>
          </div>
          <div>
            <dt>Unit Price</dt>
            <dd>{item.unitPrice ? formatPKR(item.unitPrice) : "—"}</dd>
          </div>
          <div>
            <dt>Payment Method</dt>
            <dd>{item.paymentMethod}</dd>
          </div>
          <div>
            <dt>Reference</dt>
            <dd>{item.reference || "—"}</dd>
          </div>
          <div className="transaction-detail-total">
            <dt>Total Amount</dt>
            <dd>{formatPKR(item.amount)}</dd>
          </div>
        </dl>
      </section>
    </main>
  );
}

