import type { Metadata } from "next";
import Image from "next/image";
import { PrintButton } from "@/components/print-button";
import { WhatsAppLedgerButton } from "@/components/whatsapp-ledger-button";
import { getParty } from "@/db/business-queries";
import { getWorkerWithPayments } from "@/db/operations-queries";
import { formatDate, formatPKR } from "@/lib/utils";
import {
  buildReport,
  reportTypes,
  type ReportType,
} from "@/lib/report-data";

export const metadata: Metadata = { title: "Print Report" };

export default async function PrintReportPage({
  searchParams,
}: {
  searchParams: Promise<{ type?: string; start?: string; end?: string; partyId?: string; productId?: string; workerId?: string; warehouseId?: string }>;
}) {
  const params = await searchParams;
  const type = reportTypes.includes(params.type as ReportType)
    ? (params.type as ReportType)
    : "transactions";
  const report = await buildReport(type, {
    start: params.start,
    end: params.end,
    partyId: params.partyId,
    productId: params.productId,
    workerId: params.workerId,
    warehouseId: params.warehouseId,
  });

  const partyResult = params.partyId ? await getParty(params.partyId) : null;
  const workerResult = params.workerId ? await getWorkerWithPayments(params.workerId) : null;

  const periodText = params.start || params.end
    ? `${params.start || "Beginning"} – ${params.end || "Today"}`
    : "All Time";

  const targetPhone = partyResult?.party.phone || workerResult?.worker.phone || null;

  const messageLines = [
    `Crown Accumulator - ${report.title}`,
    partyResult ? `Party: ${partyResult.party.name}` : null,
    workerResult ? `Worker: ${workerResult.worker.name} (${workerResult.worker.workerCode})` : null,
    partyResult ? `Receivable: ${formatPKR(partyResult.receivable)} | Payable: ${formatPKR(partyResult.payable)}` : null,
    workerResult ? `Monthly Salary: ${formatPKR(workerResult.worker.monthlySalary)}` : null,
    `Total Records: ${report.rows.length}`,
    `Period: ${periodText}`,
    `Generated: ${formatDate(new Date())}`,
    "",
    "Thank you. This report was generated by Crown Accumulator Management System.",
  ].filter(Boolean) as string[];

  const whatsappMessage = messageLines.join("\n");

  return (
    <main className="page printable-report-page">
      <div className="report-print-actions no-print">
        <a className="button button-secondary" href="/reports">
          Back to Reports
        </a>
        <PrintButton label="Print / Save PDF" />
        <WhatsAppLedgerButton
          phone={targetPhone}
          message={whatsappMessage}
          label="Send to WhatsApp"
        />
      </div>
      <article className="printable-report">
        <header className="print-report-head">
          <div className="invoice-brand">
            <Image className="print-brand-logo" src="/CrownAccumulatorbox.jpeg" alt="Crown Accumulator" width={300} height={291} />
            <div>
              <h1>Crown Accumulator</h1>
              <p>Battery Management System · Professional Business Solutions</p>
            </div>
          </div>
          <div className="invoice-solo">
            <Image className="solo-logo" src="/solo-removebg-preview.png" alt="SOLO" width={675} height={379} />
            <small>Powered by SOLO</small>
          </div>
        </header>
        <div className="invoice-rule" />
        <h2>{report.title}</h2>
        <div className="report-meta">
          <span>
            Generated:{" "}
            {new Intl.DateTimeFormat("en-GB", {
              dateStyle: "medium",
              timeZone: "Asia/Karachi",
            }).format(new Date())}
          </span>
          <span>Total Records: {report.rows.length}</span>
          <span>
            Period: {periodText}
          </span>
        </div>
        <div className="print-report-table-wrap">
          <table className="print-report-table">
            <thead>
              <tr>
                {report.columns.map((column) => (
                  <th key={column}>{column}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {report.rows.map((row, index) => (
                <tr key={index}>
                  {report.columns.map((column) => (
                    <td key={column}>{row[column]}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <footer className="report-footer">
          This report was generated by Crown Accumulator Management System
        </footer>
      </article>
    </main>
  );
}
