"use client";

import { ArrowLeftRight, Banknote, Boxes, Download, FileText, Package, Printer, UserCheck, Users } from "lucide-react";
import { useState } from "react";
import { WhatsAppLedgerButton } from "@/components/whatsapp-ledger-button";
import { formatPKR } from "@/lib/utils";

const reports = [
  { value: "transactions", title: "Transaction Report", description: "Detailed list of all transactions", icon: ArrowLeftRight, color: "#4169f6" },
  { value: "party-ledger", title: "Party Ledger Report", description: "Detailed ledger for one party or balance summary", icon: Users, color: "#18c77a" },
  { value: "parties", title: "Parties Report", description: "Customer and supplier information", icon: Users, color: "#ff950f" },
  { value: "products", title: "Product Report", description: "Product list with roles and current PKR prices", icon: Package, color: "#e65aa2" },
  { value: "stock", title: "Stock Report", description: "Inventory levels by product and warehouse", icon: Boxes, color: "#13b8d3" },
  { value: "inventory-movements", title: "Stock Movement History", description: "Every stock increase, decrease, sale, and purchase", icon: Boxes, color: "#0e9fbe" },
  { value: "workers", title: "Worker Report", description: "Employee list and salary information", icon: UserCheck, color: "#8754ec" },
  { value: "worker-payment-status", title: "Worker Payment Status", description: "Monthly payment status for workers", icon: UserCheck, color: "#18c79b" },
  { value: "worker-payments", title: "Worker Payment History", description: "Salary, advances, deductions, and paid balances", icon: Banknote, color: "#24b47e" },
  { value: "bank-balances", title: "Bank Balance Report", description: "Current bank and cash account balances", icon: Banknote, color: "#ef3942" },
  { value: "individual-worker", title: "Individual Worker Report", description: "Detailed report for a specific worker", icon: UserCheck, color: "#ff7615" },
] as const;

type Options = {
  parties: Array<{ id: string; name: string; phone: string | null; receivable: string; payable: string }>;
  products: Array<{ id: string; name: string; sku: string }>;
  workers: Array<{ id: string; name: string; code: string; phone?: string | null }>;
  warehouses: Array<{ id: string; name: string; code: string }>;
};

export function ReportBuilder({ options }: { options: Options }) {
  const [type, setType] = useState("transactions");
  const [partyId, setPartyId] = useState("");
  const [workerId, setWorkerId] = useState("");

  const showParty = ["transactions", "party-ledger", "parties"].includes(type);
  const showProduct = ["transactions", "products", "stock", "inventory-movements"].includes(type);
  const showWorker = ["workers", "worker-payment-status", "worker-payments", "individual-worker"].includes(type);
  const showWarehouse = ["stock", "inventory-movements"].includes(type);

  const selectedParty = options.parties.find((party) => party.id === partyId);
  const selectedWorker = options.workers.find((worker) => worker.id === workerId);
  const selectedReportTitle = reports.find((r) => r.value === type)?.title || "Report";

  const partyNet = selectedParty ? Number(selectedParty.receivable) - Number(selectedParty.payable) : 0;

  const targetPhone = selectedParty?.phone || selectedWorker?.phone || null;

  const whatsappMessage = [
    `Crown Accumulator - ${selectedReportTitle}`,
    selectedParty ? `Party: ${selectedParty.name}` : null,
    selectedParty ? `Receivable: ${formatPKR(selectedParty.receivable)} | Payable: ${formatPKR(selectedParty.payable)}` : null,
    selectedParty ? `Net Balance: ${formatPKR(Math.abs(partyNet))} ${partyNet >= 0 ? "Receivable" : "Payable"}` : null,
    selectedWorker ? `Worker: ${selectedWorker.name} (${selectedWorker.code})` : null,
    "Thank you. This report was generated by Crown Accumulator Management System.",
  ].filter(Boolean).join("\n");

  return (
    <form className="reports-layout" method="get">
      <section className="card report-picker">
        <h2>Select Report Type</h2>
        <div className="report-grid">
          {reports.map(({ value, title, description, icon: Icon, color }) => (
            <label className="report-option" key={value}>
              <input checked={type === value} name="type" onChange={() => setType(value)} type="radio" value={value} />
              <span className="report-icon" style={{ background: color }}><Icon size={23} /></span>
              <span><strong>{title}</strong><small>{description}</small></span>
            </label>
          ))}
        </div>
      </section>
      <aside className="report-controls">
        <section className="card report-date-card">
          <h2>Report Filters</h2>
          {showParty ? <div className="field"><label htmlFor="partyId">Specific Party</label><select className="select" id="partyId" name="partyId" onChange={(event) => setPartyId(event.target.value)} value={partyId}><option value="">All parties</option>{options.parties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> : null}
          {showProduct ? <div className="field"><label htmlFor="productId">Specific Product / Stock Item</label><select className="select" id="productId" name="productId" defaultValue=""><option value="">All products</option>{options.products.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.sku}</option>)}</select></div> : null}
          {showWorker ? <div className="field"><label htmlFor="workerId">Specific Worker</label><select className="select" id="workerId" name="workerId" onChange={(event) => setWorkerId(event.target.value)} value={workerId}><option value="">All workers</option>{options.workers.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select></div> : null}
          {showWarehouse ? <div className="field"><label htmlFor="warehouseId">Specific Warehouse</label><select className="select" id="warehouseId" name="warehouseId" defaultValue=""><option value="">All warehouses</option>{options.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select></div> : null}
          <div className="field"><label htmlFor="start">Start Date</label><input className="input" id="start" name="start" type="date" /></div>
          <div className="field"><label htmlFor="end">End Date</label><input className="input" id="end" name="end" type="date" /></div>
        </section>
        <section className="card export-card">
          <h2>Export Options</h2>
          <button className="button button-success" formAction="/api/reports/export" type="submit"><Download size={20} /> Download CSV</button>
          <button className="button button-primary" formAction="/reports/print" type="submit"><Printer size={20} /> Print / Save PDF</button>
          <WhatsAppLedgerButton phone={targetPhone} message={whatsappMessage} label="Send to WhatsApp" triggerPrint={false} />
          <div className="export-note"><FileText size={18} /> Filters apply to CSV, PDF, and WhatsApp sharing.</div>
        </section>
      </aside>
    </form>
  );
}
