import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { WhatsAppLedgerButton } from "@/components/whatsapp-ledger-button";
import { getBill } from "@/db/billing-queries";
import { formatDate, formatPKR } from "@/lib/utils";

export const metadata: Metadata = { title: "Bill" };

export default async function BillPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const result = await getBill(id);
  if (!result) notFound();
  const { bill, items } = result;

  const whatsappMessage = [
    `Crown Accumulator - ${bill.type === "invoice" ? "Invoice" : "Quotation"}`,
    `${bill.type === "invoice" ? "Invoice" : "Quotation"} No: ${bill.billNumber}`,
    `Date: ${formatDate(bill.billDate)}`,
    bill.dueDate ? `Due Date: ${formatDate(bill.dueDate)}` : null,
    "",
    ...items.map((item, i) => `${i + 1}. ${item.description} — Qty: ${Number(item.quantity).toLocaleString()} × ${formatPKR(item.unitPrice)} = ${formatPKR(item.lineTotal)}`),
    "",
    `Subtotal: ${formatPKR(bill.subtotal)}`,
    Number(bill.taxAmount) > 0 ? `Tax (${Number(bill.taxRate)}%): ${formatPKR(bill.taxAmount)}` : null,
    Number(bill.shippingAmount) > 0 ? `Shipping: ${formatPKR(bill.shippingAmount)}` : null,
    Number(bill.discountAmount) > 0 ? `Discount: -${formatPKR(bill.discountAmount)}` : null,
    `*Total: ${formatPKR(bill.totalAmount)}*`,
    "",
    "Thank you for your business. This bill was generated by Crown Accumulator Management System.",
  ].filter(line => line !== null).join("\n");

  return (
    <main className="page invoice-page">
      <div className="invoice-actions no-print">
        <Link className="button button-secondary" href="/bills/new">
          <ArrowLeft size={19} /> New Bill
        </Link>
        <PrintButton label="Print / Save PDF" />
        <WhatsAppLedgerButton phone={bill.party.phone} message={whatsappMessage} />
      </div>
      <article className="invoice-sheet">
        <header className="invoice-head">
          <div className="invoice-brand">
            <Image className="print-brand-logo" src="/CrownAccumulatorbox.jpeg" alt="Crown Accumulator" width={300} height={291} />
            <div>
              <h1>Crown Accumulator</h1>
              <p>Battery Manufacturing & Management System</p>
            </div>
          </div>
          <div className="invoice-solo">
            <Image className="solo-logo" src="/solo-removebg-preview.png" alt="SOLO" width={675} height={379} />
            <small>Powered by SOLO</small>
          </div>
        </header>
        <div className="invoice-rule" />
        <section className="invoice-meta">
          <div>
            <span>Bill to</span>
            <h2>{bill.party.name}</h2>
            <p>{bill.party.contactPerson}</p>
            <p>{bill.party.address}</p>
            <p>{bill.party.phone}</p>
          </div>
          <dl>
            <div>
              <dt>{bill.type === "invoice" ? "Invoice" : "Quotation"} No.</dt>
              <dd>{bill.billNumber}</dd>
            </div>
            <div>
              <dt>Date</dt>
              <dd>{formatDate(bill.billDate)}</dd>
            </div>
            <div>
              <dt>Due date</dt>
              <dd>{formatDate(bill.dueDate)}</dd>
            </div>
            <div>
              <dt>Status</dt>
              <dd className="capitalize">{bill.status}</dd>
            </div>
          </dl>
        </section>
        <table className="invoice-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Unit Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, index) => (
              <tr key={item.id}>
                <td>{index + 1}</td>
                <td>
                  <strong>{item.description}</strong>
                  {item.sku && <small>{item.sku}</small>}
                </td>
                <td>{Number(item.quantity).toLocaleString()}</td>
                <td>{formatPKR(item.unitPrice)}</td>
                <td>{formatPKR(item.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <section className="invoice-totals">
          <dl>
            <div>
              <dt>Subtotal</dt>
              <dd>{formatPKR(bill.subtotal)}</dd>
            </div>
            <div>
              <dt>Tax ({Number(bill.taxRate)}%)</dt>
              <dd>{formatPKR(bill.taxAmount)}</dd>
            </div>
            {Number(bill.shippingAmount) > 0 && (
              <div>
                <dt>Shipping</dt>
                <dd>{formatPKR(bill.shippingAmount)}</dd>
              </div>
            )}
            {Number(bill.discountAmount) > 0 && (
              <div>
                <dt>Discount</dt>
                <dd>− {formatPKR(bill.discountAmount)}</dd>
              </div>
            )}
            <div className="invoice-total">
              <dt>Total</dt>
              <dd>{formatPKR(bill.totalAmount)}</dd>
            </div>
          </dl>
        </section>
        {bill.notes && (
          <section className="invoice-notes">
            <strong>Notes / Terms</strong>
            <p>{bill.notes}</p>
          </section>
        )}
        <footer className="invoice-footer">
          <p>Prepared by {bill.createdBy}</p>
          <p>Thank you for your business.</p>
        </footer>
      </article>
    </main>
  );
}
